### ISSUE TITLE
@maxxibull is lazy 

### ISSUE THREAD

**Issue by adimus11** [narolski/furtive#5]
Maxibull is quite a lazy guy in terms of code quality, I think it's critical issue as it's happening on the production environment.

@Adimus11 @JakubGogola love u & your suggestions, but I have no more time for studying :)

_Originally posted by @maxxibull in https://github.com/narolski/furtive/pull/4#issuecomment-649560846_

**Comment by JakubGogola** [comment]
@Adimus11 ad Please also add versions of Go and your system where this issue occurrs

**Comment by adimus11** [comment]
> @Adimus11 ad Please also add versions of Go and your system where this issue occurrs

Go version from initial release to 1.14, operating system macOS 10.14, MB Pro 15 2018

**Comment by Sernikjamnika** [comment]
@Adimus11 what do you think about replacing @maxxibull with his guinea pigs?

**Comment by JakubGogola** [comment]
Our support team is working on fix for this issue but I’m afraid we need to apply „jebanie Kustosza na bulwarze” to @maxxibull to fix this critical bug.

**Comment by adimus11** [comment]
> @Adimus11 what do you think about replacing @maxxibull with his guinea pigs?

Could fix the issue with performance but then we are going to struggle live with the memory leaks :/

**Comment by okkindel** [comment]
I suspect @maxxibull is still much more active than at work, let him rest a bit.

**Comment by narolski** [comment]
@Adimus11 I believe that a new, government-backed motivational programme "1 kustosz per 1 approved PR" is needed to resolve this urgent issue.

@JakubGogola, can you confirm that this issue may be resolved by such a proposal?

**Comment by JakubGogola** [comment]
Yup, It definitely can help

**Comment by Sernikjamnika** [comment]
@narolski in my opinion it is going to be a tremendous improvement in speed of approving PRs but quality can become our next problem.

**Comment by Sernikjamnika** [comment]
The programme should be "1 kustosz per 1 approved PR and 5 more for spotted bug"

**Comment by narolski** [comment]
@Sernikjamnika Not to worry - I've just made `master` a protected branch, and I do sincerely hope that our quality assurance process with help of @Adimus11 and @JakubGogola will hold a highest standard of "actually do giving a care for this crypto project".

**Comment by narolski** [comment]
Closing since an appropriate solution has been found. @JakubGogola will validate the total number of `kustosze` granted for all successful merges after the project is completed.
